postgres:
  image: postgres:11.10
  container_name: todo-postgres
  ports:
    - 5432:5432
  # if you want to persist data
  volumes:
    - ./.docker/postgres:/var/lib/postgresql/data
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: password
    POSTGRES_DB: todo
    POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
  restart: always
