postgres:
  image: postgres:11.10
  container_name: todo-postgres
  ports:
    - 5432:5432
#  volumes:
#    - ./postgres/init:/docker-entrypoint-initdb.d
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: password
    POSTGRES_DB: todo
    POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
  restart: always
